### ISSUE TITLE
The application is not responding

### ISSUE THREAD

**Issue by 0riginull1** [ffouqueray/Translator-Bot#1]
Hey! The application is not responding and it appears Offline on the member list for a few hours now.

![2024-02-05 at 20 17 32](https://github.com/ffouqueray/Translator-Bot/assets/134965346/e384ebcb-d315-4e70-8bdf-be4fa624e949)

**Comment by UnBonWhisky** [comment]
This is now fixed !
![image](https://github.com/ffouqueray/Translator-Bot/assets/65244389/a37e1a5c-6ff6-4693-a84a-a03b4526c136)
