### ISSUE TITLE
Translator Bot says "loading options failed" when trying to link channels

### ISSUE THREAD

**Issue by Spilner78** [ffouqueray/Translator-Bot#11]
Translator bot says "loading options failed" when trying to load languages to link two channels in Discord together.  It is being incredibly slow as well.  I tried /stats command and it failed once, then worked the second time.  Got an error that said the bot failed to respond.  The bot was working fine yesterday.

**Comment by UnBonWhisky** [comment]
Hello !

I have to upgrade the RAM of my server in order to make the bot smooth. I will do it the next month. If the issue persits, do not hesitate to comment this issue (I let it open until I upgrade)

**Comment by Spilner78** [comment]
Quick question, how many channel links are allowed per server?

**Comment by UnBonWhisky** [comment]
You can link up to 2 linkchannels.

I explain more : 
You have these 4 channels on your server :  
- chan1 - english
- chan2 - french
- chan3 - russian
- chan4 - chinese

At the same moment :  
You can link chan1 with chan2 (english <-> french)
You can link chan3 with chan4 (russian <-> chinese)

But you can not link chan1 with chan2 with chan3 (english <-> french <-> russian)

This is currently not possible on the bot. The limit is set to 1 input language, and 1 output language.

I am currently working on a premium version of thr bot (same one, just more paid only features) that will allow you to achieve this goal

**Comment by Spilner78** [comment]
So if I wanted to link an English channel with 8 other languages, this is not possible?

**Comment by UnBonWhisky** [comment]
Currently no, this is not possible, but I work on it

**Comment by Spilner78** [comment]
OK thanks.

**Comment by UnBonWhisky** [comment]
The feature is now on the bot and the RAM has been upgraded on the server.
