### ISSUE TITLE
Allow /translatechoice to be set globally, not just per user

### ISSUE THREAD

**Issue by RobinPC** [ffouqueray/Translator-Bot#4]
Hello. 

I would like the option to set the translate choice to the channel for all members by default. I understand each individual user now has to set this manually which can be a pain, unless I am missing something?

Thanks in advance

**Comment by UnBonWhisky** [comment]
Hello @RobinPC !
If you are a server administrator, you can use the force argument of the /allowflag command to force the reaction of the messages to be sent in channel / DM.
This option work for the server globally (not for a channel only).

Have a good day !

**Comment by RobinPC** [comment]
Thanks for the quick response! That did the trick, I completely overlooked the additional argument.

Thanks again.
