### ISSUE TITLE
Bot not translating/responding

### ISSUE THREAD

**Issue by hannahbanana93** [ffouqueray/Translator-Bot#5]
Bot is online, but not translating with the flag emojis.

**Comment by UnBonWhisky** [comment]
Hello !
I have tried right now and it is working.
One of the reason can be a permission issue for the channel or for the server. Try to give admin permissions on the bot to confirm me it is a permission issue.

**Comment by hannahbanana93** [comment]
It hasn’t had admin permission since it’s been on the server and was working before. Would that still be a permission issue?

**Comment by UnBonWhisky** [comment]
Docyou experience issue on all flag or only one ?
Can you please do a test with admin rights and confirm me it is not a permission issue ?

**Comment by hannahbanana93** [comment]
It’s not a permission issue, permissions are all set. Seems like it’s only working with the flag emoji on new messages. I can’t go back and translate old messages with the flag. And it’s all flags.
