### ISSUE TITLE
Translate to more channels

### ISSUE THREAD

**Issue by rrvk** [ffouqueray/Translator-Bot#8]
Hi, 

Thanks for all the work! Is it posiable to translate a channel through mulyple language channels. 
For example

- generalEnglish
- generalGerman
- generalFrench
- etc..

I tryed the /linkchannels command but you can only chain 2 channels. 
For example english -> german
But you cant add a english -> french

And you also cant chain them so like this:
english -> german
german -> french

Is something like this posible?

**Comment by UnBonWhisky** [comment]
Hello,
Actually this is not possible except if you start your own instances of the bot.
One way would be to start 2 or 3 instances of the bot, with this, you should be able to achieve what you are looking for, but for now, I can not provide any ETA of the release of this feature.
